

POST http://localhost:3000/users
Content-Type: application/json
Authorization: = 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IklSWlZ1V0hoQ015ZU5NNUhuaFoyVyJ9.eyJpc3MiOiJodHRwczovL2Rldi00OXJ1dHVoZy51cy5hdXRoMC5jb20vIiwic3ViIjoiNjU5aUJkVnN5c3lmbXFrZWNNSVV3eE5rdTdjOE1IUjlAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vcmFpbHMtc2VjdXJlLWFwaSIsImlhdCI6MTYzMTk3NDg0MSwiZXhwIjoxNjMyMDYxMjQxLCJhenAiOiI2NTlpQmRWc3lzeWZtcWtlY01JVXd4Tmt1N2M4TUhSOSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.IWy6GIOd6xf00aQvrsZy92_PiNPvKkb0Asxjdw7T9d_eJ0HtO-ASTSD2-jA5xXYsXMWqTk3oI7mD3V1nr0tcFy5_dPxbjFdMvinyOVHEpZN3hIW9zS8kVV5zIXZBkTwXHvaaXi7D8kY6eOETYCQEspVybFmhTO-nVHchFUWp9G_nyeg16Xrlw-MuSnsfAUSZ8ZKwCsXKI1Rb-2Bne2ck3B_1ifORTOD6BeqGFLLR4QyEQNWIilCW23jgcKyrm-thrX_PPsLFsHu88lfuoAG-Kg8aEBuawhWtpOmU8wcAvI1wnqJAwSvqbuOIzHJP3vd_hcXHe2siUVSsu7NDrDAaOg'

{
    "email": "test@track.com",
    "username":"password"
}
